version: '3.9'

services: 
  django:
    container_name: django
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment: 
      - DJANGO_SETTINGS_MODULE=config.settings
  react:
    container_name: react
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 3001:3000
