version: '3.9'

services: 
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver
    volumes:
      - .:app/backend/
    ports:
      - 8000:8000
    environment: 
      - DJANGO_SETTINGS_MODULE=config.settings
  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:app/frontend/
    ports:
      - 3001:3000
