version: '3.9'

services:
  django:
    container_name: django
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - DJANGO_SETTINGS_MODULE=config.settings
    links:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=backend-dev
    volumes:
      - ./mongo:/data/db

  react:
    container_name: react
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 3001:3000
