name: Django CI

on: 
  push:
    branches-ignore:
      - "develop"
      - "master"
  pull_request:
    branches:
      - "develop"
      - "master"

jobs:
  test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        mongodb-version: [3.6, 4.0, 4.2, 4.4]

    steps:

    - uses: actions/checkout@v2
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.4.1
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-port: 27017
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest-django
    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_SETTINGS_MODULE: config.settings
      run: coverage run -m pytest
    - name: Coverage report
      run: coverage report